import type { Metadata } from 'next';
import './globals.css';
import RootLayoutProvider from '@/shared/components/provider/RootLayoutProvider';
import GlobalLayout from '@/shared/components/layout/GlobalLayout';

export const metadata: Metadata = {
  title: '나와놀자',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <RootLayoutProvider>
          <GlobalLayout>{children}</GlobalLayout>
        </RootLayoutProvider>
      </body>
    </html>
  );
}
